
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/Shopify/go-lua"

[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  branch = "develop"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/go-errors/errors"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.7.2"

[[constraint]]
  branch = "master"
  name = "github.com/googollee/go-socket.io"

[[constraint]]
  branch = "master"
  name = "github.com/jonas747/dca"

[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  version = "1.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/nishanths/go-xkcd"

[[constraint]]
  branch = "master"
  name = "github.com/robertkrimen/otto"

[[constraint]]
  name = "github.com/rylio/ytdl"
  version = "0.5.1"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/buntdb"

[[constraint]]
  branch = "master"
  name = "github.com/tidwall/redcon"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
